#!/bin/bash

# Start the infinite loop script
./4-to_infinity_and_beyond &

# Capture the PID of the background process
bg_process_pid=$!

# Run the "stop me if you can" script in another terminal
./6-stop_me_if_you_can

# Stop the infinite loop process without using kill
exec 3>&1 4>&2 > /proc/"$bg_process_pid"/fd/1 2> /proc/"$bg_process_pid"/fd/2 && exec 1>&3 2>&4

# Notify that the process has been terminated
echo "Terminated"
