#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initialize a counter
count=0

# Use an until loop to display "Best School" 10 times
until [ $count -eq 10 ]; do
    echo "Best School"
    ((count++))
done
