#!/usr/bin/env bash
grep -q '^nginx:' /etc/group || groupadd -g 101 nginx
id -u nginx &>/dev/null || useradd -u 101 -g nginx nginx
mkdir -p /etc/nginx/sites-available
echo "server {
    listen 8080;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default
echo "user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}" > /etc/nginx/nginx.conf
sleep 1
nginx
